### ISSUE TITLE
Overflow issues

### ISSUE THREAD

**Issue by sir-captainmorgan21** [cliedelt/storybook-addon-docs-tabs#1]
Thanks for this addon. Its worked great. I've noticed a couple of overflow issues though. For horizontal overflow, I noticed you added negative margins to offset the padding and align the content flush with the edges. This cuts off args tables. I ended up writing css to remove this negative margins, but would love to see that cleaned up so we dont have to maintain that. I actually think it looks ok indented a bit.

The second piece is vertical overflow at the bottom if "showCode" is expanded, and the code snippet is anything more than a few lines. I know its an issue with the tab content being an iframe, so not sure the solution here.

**Comment by sir-captainmorgan21** [comment]
https://mdxjs.com/docs/using-mdx/#components here it says "Because MDX files are components, they can also import each other:". Can we not render the mdx file like in the example?

**Comment by cliedelt** [comment]
Hi @sir-captainmorgan21! Thank you for submitting this first issue.

> Thanks for this addon. Its worked great. I've noticed a couple of overflow issues though. For horizontal overflow, I noticed you added negative margins to offset the padding and align the content flush with the edges. This cuts off args tables. I ended up writing css to remove this negative margins, but would love to see that cleaned up so we dont have to maintain that. I actually think it looks ok indented a bit.
> 
> The second piece is vertical overflow at the bottom if "showCode" is expanded, and the code snippet is anything more than a few lines. I know its an issue with the tab content being an iframe, so not sure the solution here.

I will look into it today. Expect a fix in the next hours/days. If you could provide a sample or screenshot would help much!

> https://mdxjs.com/docs/using-mdx/#components here it says "Because MDX files are components, they can also import each other:". Can we not render the mdx file like in the example?
 
I would love to switch to this approach. I works for mdx. But not with storybook... Storybook requires a context provided to stories inside the mdx file. I tried to dig deep into the storybook code but the storybook api is very very narrow.

**Comment by sir-captainmorgan21** [comment]
@cliedelt sure thing!
> I will look into it today. Expect a fix in the next hours/days. If you could provide a sample or screenshot would help much!
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/7041924/155200363-f91fe502-8226-48b5-b170-855c3bd4d918.png">

> I would love to switch to this approach. I works for mdx. But not with storybook... Storybook requires a context provided to stories inside the mdx file. I tried to dig deep into the storybook code but the storybook api is very very narrow.

Ahh ok. Maybe some help can be provided in the discord? I will try to pull in someone from storybook too

**Comment by cliedelt** [comment]
Thank you for the screenshot ! Im fixing it right now.

Sure! Im would be very happy to improve the logic of the addon with a deeper storybook integration.  My discord is Architect#9240.

**Comment by sir-captainmorgan21** [comment]
@cliedelt Awesome thanks!
