### ISSUE TITLE
Optional Description

### ISSUE THREAD

**Issue by chogland** [cliedelt/storybook-addon-docs-tabs#6]
I would like to add an optional description so that I can define a description for a component and not have it redundantly placed on both/either tab's MDX.

I have a branch locally ready with this update but it denied access to push up a branch in order to create a pull request.

Thanks,
 - Charlie

**Comment by chogland** [comment]
Something like this: 
`export default function Header(props: {
  title: string;
  description: string;
  additionalElement?: Node;
}) {
  return (
    <div className="storybook_header_container">
      <div className="storybook_header">
        <h1>{props.title}</h1>
        {props.description ? <p>{props.description}</p> : null}
        {props.additionalElement}
      </div>
    </div>
  );
}`

**Comment by cliedelt** [comment]
Sounds awesome. I dont know why you get a denied access.. Make sure to fork the repo and then do a pull request... I could not find a fork in your account of this repo.

**Comment by chogland** [comment]
@cliedelt I have submitted a pull request. Please let me know if that will do the trick :-)
