### ISSUE TITLE
Transitioning from MDX via Tabs is very slow.

### ISSUE THREAD

**Issue by chogland** [cliedelt/storybook-addon-docs-tabs#7]
![Tabs Issue](https://user-images.githubusercontent.com/5976480/194867198-21bad33b-b0d2-4eea-aaf2-818a5841a46c.gif)

Please notice the delay from initial load and from tab to tab. Anyway to speed this up?

**Comment by cliedelt** [comment]
Well... The current logic is pretty hacky tbh... There are multiple iframe inside each other. To make this work much better, would be to use the storybook api. Unfortunately storybook does not offer such api so I had to go with this hack..

**Comment by chogland** [comment]
Thankfully, its MUCH faster when out of dev mode. thank you
